<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
      <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
      <GenerateTargetFramework>false</GenerateTargetFramework>
      <PlatformTarget>x64</PlatformTarget>
      <Platforms>x64</Platforms>
      <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="intiface-engine.exe" />
    <None Remove="Resources\actions\actions.json" />
    <None Remove="Resources\actions\bindings_holographic_controller.json" />
    <None Remove="Resources\actions\bindings_knuckles.json" />
    <None Remove="Resources\actions\bindings_logitech_stylus.json" />
    <None Remove="Resources\actions\bindings_oculus_touch.json" />
    <None Remove="Resources\actions\bindings_vive_controller.json" />
    <None Remove="Resources\actions\bindings_vive_cosmos_controller.json" />
    <None Remove="Resources\actions\binding_holographic_hmd.json" />
    <None Remove="Resources\actions\binding_index_hmd.json" />
    <None Remove="Resources\actions\binding_rift.json" />
    <None Remove="Resources\actions\binding_vive.json" />
    <None Remove="Resources\actions\binding_vive_cosmos.json" />
    <None Remove="Resources\actions\binding_vive_pro.json" />
    <None Remove="Resources\actions\binding_vive_tracker_camera.json" />
    <None Remove="Resources\HPUI.dll" />
    <None Remove="Resources\OpenVRSettings.asset" />
    <None Remove="Resources\openvr_api.dll" />
    <None Remove="Resources\SteamVR_Melon.assets" />
    <None Remove="Resources\SteamVR_Melon.dll" />
    <None Remove="Resources\SteamXR_Melon.dll" />
    <None Remove="Resources\System.Security.Permissions.dll" />
    <None Remove="Resources\System.Threading.Channels.dll" />
    <None Remove="Resources\ucrtbased.dll" />
    <None Remove="Resources\UnitySubsystemsManifest.json" />
    <None Remove="Resources\vrshaders\vrshaders" />
    <None Remove="Resources\vrshaders\vrshaders.manifest" />
    <None Remove="Resources\XRSDKOpenVR.dll" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\actions\actions.json" />
    <EmbeddedResource Include="Resources\actions\bindings_holographic_controller.json" />
    <EmbeddedResource Include="Resources\actions\bindings_knuckles.json" />
    <EmbeddedResource Include="Resources\actions\bindings_logitech_stylus.json" />
    <EmbeddedResource Include="Resources\actions\bindings_oculus_touch.json" />
    <EmbeddedResource Include="Resources\actions\bindings_vive_controller.json" />
    <EmbeddedResource Include="Resources\actions\bindings_vive_cosmos_controller.json" />
    <EmbeddedResource Include="Resources\actions\binding_holographic_hmd.json" />
    <EmbeddedResource Include="Resources\actions\binding_index_hmd.json" />
    <EmbeddedResource Include="Resources\actions\binding_rift.json" />
    <EmbeddedResource Include="Resources\actions\binding_vive.json" />
    <EmbeddedResource Include="Resources\actions\binding_vive_cosmos.json" />
    <EmbeddedResource Include="Resources\actions\binding_vive_pro.json" />
    <EmbeddedResource Include="Resources\actions\binding_vive_tracker_camera.json" />
    <EmbeddedResource Include="Resources\HPUI.dll" />
    <EmbeddedResource Include="Resources\OpenVRSettings.asset" />
    <EmbeddedResource Include="Resources\openvr_api.dll" />
    <EmbeddedResource Include="Resources\SteamVR_Melon.assets" />
    <EmbeddedResource Include="Resources\SteamVR_Melon.dll" />
    <EmbeddedResource Include="Resources\SteamXR_Melon.dll" />
    <EmbeddedResource Include="Resources\System.Security.Permissions.dll" />
    <EmbeddedResource Include="Resources\System.Threading.Channels.dll" />
    <EmbeddedResource Include="Resources\ucrtbased.dll" />
    <EmbeddedResource Include="Resources\UnitySubsystemsManifest.json" />
    <EmbeddedResource Include="Resources\vrshaders\vrshaders" />
    <EmbeddedResource Include="Resources\vrshaders\vrshaders.manifest" />
    <EmbeddedResource Include="Resources\XRSDKOpenVR.dll" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="HPUI">
      <HintPath>..\HPUI\bin\Release\net6.0\HPUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppEekCharacterEngine">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\Il2CppEekCharacterEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppEekEvents">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\Il2CppEekEvents.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppEekUI">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\Il2CppEekUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppHouseParty">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\Il2CppHouseParty.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\Il2CppSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\net6\MelonLoader.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\Unity.InputSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\UnityEngine.AudioModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.Il2CppAssetBundleManager">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\net6\UnityEngine.Il2CppAssetBundleManager.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.SubsystemsModule">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\UnityEngine.SubsystemsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>G:\SteamLibrary\steamapps\common\House Party\MelonLoader\Il2CppAssemblies\UnityEngine.UIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SteamVR_Melon\SteamVR_Melon.csproj" />
    <ProjectReference Include="..\SteamXR_Melon\SteamXR_Melon.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy .\bin\x64\Debug\net6.0\HPVR.dll &quot;G:\SteamLibrary\steamapps\common\House Party\Mods\HPVR.dll&quot; /y &amp; del &quot;G:\SteamLibrary\steamapps\common\House Party\HouseParty_Data\StreamingAssets\SteamVR\OpenVRSettings.asset&quot;" />
  </Target>

</Project>
